### PR TITLE
[24_6] fix underline missing bug

### PR DESCRIPTION
**Pull request by Charonxin**
## Why you open this Pull Request?

Close: #499

### CODE REVIEW

**Review by jingkaimori — CHANGES_REQUESTED** [review]
This patch is contributed by Philippe Joyez,you should add him as co-author of this pr, by appending such text at the end of commit:

```
Co-authored-by: Philippe Joyez <coding.e.pjoyez@neverbox.com>
```

**Comment by Charonxin** [comment]
> This patch is contributed by Philippe Joyez,you should add him as co-author of this pr, by appending such text at the end of commit:
> 
> ```
> Co-authored-by: Philippe Joyez <coding.e.pjoyez@neverbox.com>
> ```

done.

**Review by jingkaimori — CHANGES_REQUESTED** [review]
> However, this does not work when the decorated text spans over several paragraphs; needs more work.

[testcase.zip](https://github.com/XmacsLabs/mogan/files/12802728/texmacsTest.zip)

**Comment by darcy-shen** [comment]
单元测试需要增加一下

**Comment by darcy-shen** [comment]
`24_1`这个编号已经占用了，需要另外的编号

**Comment by darcy-shen** [comment]
除了没有单元测试，代码缩进也是一个问题

**Comment by darcy-shen** [comment]
Let me merge it and improve it later

**Review by darcy-shen — APPROVED** [review]
LGTM

**Pull request merged**
