### PR TITLE
Implemented a unit test for ospp project

### PR DESCRIPTION
**Pull request by rachelxhoot**

### CODE REVIEW

**Comment by mgubi** [comment]
This is not a good test, I would suggest to not integrate it. It does not test any meaningful Mogan functionality. Maybe we should make clear the goals of this exercise, that is to show that an applicant to SoC understand some of the Mogan's internals enough to write meaningful and *useful* tests.

**Comment by rachelxhoot** [comment]
I'm sorry that I thought this was just to show I know how to submit PR on Github and understand unit testing, but it wasn't really meant to merge in.

**Comment by da-liii** [comment]
> This is not a good test

@rachelxhoot It could be improved and become a good unit test. You can reopen this pull request and move on. Do not be afraid that you are writing the wrong code.

**Comment by da-liii** [comment]
For example, https://github.com/XmacsLabs/mogan/pulls?q=7_2

I was writing the wrong code for the task `7_2`, and I finally make it correct.

For software engineering, we'd better be direct, wrong is wrong, correct is correct.

**Comment by rachelxhoot** [comment]
> For example, https://github.com/XmacsLabs/mogan/pulls?q=7_2
> 
> I was writing the wrong code for the task `7_2`, and I finally make it correct.
> 
> For software engineering, we'd better be direct and honest, wrong is wrong, correct is correct. Wrong code is not a problem, with proper code review, we should prevent it from being merged.

Thank you very much for your guidance :) I will work on improving it.

**Pull request closed without merging**
