### PR TITLE
upgrade cmake version

### PR DESCRIPTION
**Pull request by PikachuHy**

### CODE REVIEW

**Comment by PikachuHy** [comment]
sub pr of https://github.com/XmacsLabs/mogan/pull/123

**Comment by darcy-shen** [comment]
Why we need to upgrade the CMake version? What feature does CMake 3.15 brings?

**Comment by PikachuHy** [comment]
> Why we need to upgrade the CMake version? What feature does CMake 3.15 brings?

after CMake 3.15, the target-based feature is considered relatively complete.

**Review by darcy-shen — APPROVED** [review]
LGTM

**Pull request merged**
