### PR TITLE
warning: deprecated: please use includes(@builtin/check) instead of i…

### PR DESCRIPTION
**Pull request by Oyyko**
…ncludes(check_cxxtypes.lua)

## Why you open this Pull Request?

Adapt to changes in new versions of xmake

### CODE REVIEW

**Comment by Oyyko** [comment]
in 2.8.3, we don't need this. So all CI failed...

**Comment by Oyyko** [comment]
But in the newest xmake, we need to make this change.

**Comment by darcy-shen** [comment]
Let us wait for the official release of xmake 2.8.4

**Comment by jingkaimori** [comment]
Content of this PR has been added into mogan by 49_10(#1334 #1333), thus close this PR.

**Pull request closed without merging**
