### PR TITLE
[85] S7: upgrade from 9.12 to 10.5 15min

### PR DESCRIPTION
**Pull request by jingkaimori**

### CODE REVIEW

**Comment by darcy-shen** [comment]
At least, describe explicitly on the old S7 version and the new S7 version. And please run all scheme unit tests manually, because it is not tested in CI.

**Comment by darcy-shen** [comment]
This is a brief doc on how to run all scheme unit tests: https://github.com/XmacsLabs/mogan/tree/main/tests

**Comment by jingkaimori** [comment]
test runned and everything fine.

**Comment by jingkaimori** [comment]
the new version of s7 should behave similar as old version, with improved performance

**Comment by darcy-shen** [comment]
> the new version of s7 should behave similar as old version, with improved performance

describe it in `doc/devel/85.tm` briefly or in detail.

**Review by darcy-shen — CHANGES_REQUESTED** [review]
A Feature must be documented

**Review by darcy-shen — APPROVED** [review]

**Pull request merged**
