### PR TITLE
Rewrite cmake

### PR DESCRIPTION
**Pull request by PikachuHy**
see https://github.com/XmacsLabs/mogan/issues/122

DONE

- upgrade the minimum CMake version to 5.15
- set default c++ standard to 17, although TeXmacs don't use c++17 features.
- for all dependencies, use the target-based style, which can manage headers and libraries automatically.
- initial support for Qt6. However, some APIs in Qt6 have changed. We need some guards or rewrite some code.
- delete old `FindXXX.cmake`. The latest CMake has already contained them.
- two extra empty `.cpp` files. Usually, one Qt class, one `.h/.cpp` file. 

TODO

- rewrite `FindCairo.cmake`
- rewrite `FindGMP.cmake`
- rewrite `FindImlib2.cmake`

It seems that the Mogan does not use any of them.
The GMP is not a necessary dependency for S7.

- eliminate hardcode config, e.g. `CONFIG_HOST_OS`
- eliminate redundant prefix `${TEXMACS_SOURCE_DIR}` when collecting source code files.

The file path will be handled by CMake automatically after 5.15.

### CODE REVIEW

**Comment by darcy-shen** [comment]
I suggest that you should break down this pull requests into small PRs. Small PRs are more friendly for reviewers.

**Comment by darcy-shen** [comment]
I suggest that you should break down this pull requests into small PRs. Small PRs are more friendly for reviewers.

**Comment by PikachuHy** [comment]
first, replace all global variables with targets

https://github.com/XmacsLabs/mogan/pull/131

**Comment by PikachuHy** [comment]
second, upgrade CMake version
https://github.com/XmacsLabs/mogan/pull/134

**Comment by PikachuHy** [comment]
third, upgrade c++ standard
https://github.com/XmacsLabs/mogan/pull/137

**Pull request closed without merging**
