### PR TITLE
Add delete word shortcut

### LINKED ISSUE #317: Ctrl+backspace delete a word as in Emacs
Very useful!!

### PR DESCRIPTION
**Pull request by ice1000**
Fix #317 see also #375

### CODE REVIEW

**Comment by darcy-shen** [comment]
Currently, CI only works for C++. You can use the prefix `[no ci]` in the commit message to disable CI.

**Review by darcy-shen — CHANGES_REQUESTED** [review]
Here is the right place to maintain Emacs-style key-bindings.

And in emacs, the corresponding elisp function is `backward-kill-word` and `kill-word`.

https://github.com/XmacsLabs/mogan/blob/bc0051a366b58032cf8ce178fbcd367ab37f8993/TeXmacs/progs/generic/generic-kbd.scm#L266-L270

**Comment by ice1000** [comment]
> And in emacs, the corresponding elisp function is backward-kill-word and kill-word.

I tried to grep these names but I didn't find them

**Review by darcy-shen — APPROVED** [review]
LGTM

**Pull request merged**
