### PR TITLE
[134] Table: Fix the width of the joined cell 10h

### PR DESCRIPTION
**Pull request by darcy-shen**
Note: the commented debug code snippets are reserved to show `How the developer was debugging`.

Convention: 134.tm describes about the bug.

Descriptions should be kept out of Github, that's why we kept the bug desc in 134.tm.

### CODE REVIEW

**Comment by darcy-shen** [comment]
@mgubi 

Could help review this pull requests?

Currently there are 4 mogan developers: @darcy-shen , @jingkaimori , @Yufeng-shen  and @PikachuHy .
None of the requested reviewers have experience on the typesetting of table.

Furthermore, are you interested in join us on Mogan Development? I think we can show the Github workflow via Mogan and finally, we can migrate GNU TeXmacs from SVN to git. And Mogan Developers could work directly on GNU TeXmacs. eg. https://github.com/texmacs/texmacs

Github might be a good choice for GNU TeXmacs. But I do think Git is a good choice for GNU TeXmacs.

**Comment by darcy-shen** [comment]
Let me merge it now, I will release Mogan v1.1.2 beta1 today.

**Comment by mgubi** [comment]
Sorry I see only now. I'm also not expert in this, I would need some time to understand the issue and verify the fix. I'm interested in contributing to Mogan, I think is a good way to have more people involved in development and still retain a solid and stable base in TeXmacs where the usual workflow applies. I do not know if Joris has plans to move to git.

**Comment by darcy-shen** [comment]
Invitation to https://github.com/orgs/XmacsLabs/teams/mogan-developers was just sent.

Welcome to become a Mogan Developer.

**Comment by darcy-shen** [comment]
I just add a new doc on Git Workflow:
https://github.com/XmacsLabs/mogan/blob/main/docs/guide/Git.md

Github is one of the hosting service for Mogan. Welcome to add more Git hosting service.

**Pull request merged**
