### PR TITLE
qt6 matrix config

### PR DESCRIPTION
**Pull request by jingkaimori**

### CODE REVIEW

**Comment by darcy-shen** [comment]
Separate the pull request into several pull requests like:
+ One for Windows
+ One for GNU/Linux
+ One for macOS

For each pull request, we should carefully test the Qt 6 version and report the status.

**Comment by jingkaimori** [comment]
All qt6 build via xmake failed, because qt image support test fails on linux and macos:
```
 ********* Start testing of TestQtUtilities *********
Config: Using QtTest library 6.4.1, Qt 6.4.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.3.1 20210422 (Red Hat 10.3.1-1)), ubuntu 22.04
PASS   : TestQtUtilities::initTestCase()
FAIL!  : TestQtUtilities::test_qt_supports() 'qt_supports (url ("x.webp"))' returned FALSE. ()
   Loc: [tests/Plugins/Qt/qt_utilities_test.cpp(28)]
PASS   : TestQtUtilities::test_to_qurl()
PASS   : TestQtUtilities::cleanupTestCase()
Totals: 3 passed, 1 failed, 0 skipped, 0 blacklisted, 5ms
********* Finished testing of TestQtUtilities *********
```

And test throws several error on windows:
```
Throwing list too short
-------------------------------------------------

-------------------------------------------------
Throwing empty path
-------------------------------------------------

-------------------------------------------------
Throwing empty path
-------------------------------------------------

-------------------------------------------------
Throwing empty path
-------------------------------------------------

-------------------------------------------------
Throwing list too short to get the head
-------------------------------------------------

-------------------------------------------------
Throwing list too short to get the tail
-------------------------------------------------

-------------------------------------------------
```

**Comment by darcy-shen** [comment]
Please separate the pull request into three pull requests. CI pass does not mean it works. We should test it by launch it and use it.

**Comment by jingkaimori** [comment]
> Please separate the pull request into three pull requests.

Maybe we should split three jobs into separate workflow first.

**Comment by darcy-shen** [comment]
> Maybe we should split three jobs into separate workflow first.

Yes. There should be three yml file.

**Pull request closed without merging**
