### PR TITLE
[7_8] fix crashing caused by missing gs binary on windows

### PR DESCRIPTION
**Pull request by jingkaimori**
## Why you open this Pull Request?

Fix the first issue in https://gitee.com/XmacsLabs/mogan/issues/I8MZW1 , fix crashing when exporting given document to pdf. But export fails after this patch.

## What work have you done in the current Pull Request?

- [x] handle situation of missing ghostscript under default install position

### CODE REVIEW

**Comment by darcy-shen** [comment]
The problem here is why export to PDF will call gs. There are no ps images in the welcome doc.

**Comment by darcy-shen** [comment]
> the first issue 

What is the first issue specified in gitee? Do you mean the gs issue?

**Comment by jingkaimori** [comment]
> > the first issue
> 
> What is the first issue specified in gitee? Do you mean the gs issue?

I mean the crashing issue.

**Comment by jingkaimori** [comment]
gs is invoked by `image_to_pdf`

**Pull request merged**
