### PR TITLE
[70_14] Fix the retrieval and processing of the root node in lang_parser

### PR DESCRIPTION
**Pull request by UnbSky**
## What

1. `get_root_node` relies on the result of `get_child_env` to determine whether it is a code node.
2. Fixed `get_code_from_root` and `get_data_from_root` to support string nodes.
3. Fixed a minor bug in `add_single_token`.

## Why
Incorrect code root node can lead to performance degradation, rendering errors, and PDF export failures.
## How to test your changes?
Use Syntax Highlight

### CODE REVIEW

**Comment by da-liii** [comment]
性能实测，没什么问题了。使用 https://github.com/LiiiLabs/goldfish/blob/main/Goldfish.tmu 测试，效果很好

**Comment by da-liii** [comment]
现在的代码存在严重的问题，插入Scheme会话，然后运行就会直接Crash

image

此时，按下回车键，就会直接crash，终端显示是排版错误

**Comment by UnbSky** [comment]
> 现在的代码（这个pr）存在严重的问题，插入Scheme会话，然后运行就会直接Crash
> 
> image
> 
> 此时，按下回车键，就会直接crash，终端显示是排版错误。关闭ast syntax highlight之后，旧的代码没问题： image

Fixed

**Review by jingkaimori — APPROVED** [review]
LGTM, session itself should be improved in another pr

**Pull request merged**
