### PR TITLE
xmake: dev guide on GNU/Linux 45m

### PR DESCRIPTION
**Pull request by darcy-shen**

### CODE REVIEW

**Comment by jingkaimori** [comment]
package feature should be described.
```sh
xmake install mogan_install
./build/package/bin/mogan
```

**Comment by darcy-shen** [comment]
This pull request only aim to describe about the dev guide. On GNU/Linux, packaging is different for different Linux distro.

**Comment by darcy-shen** [comment]
On Debian, `xmake install mogan_install` will install to `/usr/local`.

**Comment by darcy-shen** [comment]
Do you mean like windows:

```
xmake install -o build/package mogan_install
```
And then launch it via 
```
build/package/bin/mogan
```

**Pull request merged**
