### PR TITLE
[23_1] Fix ellipse, arc, circle inner color

### PR DESCRIPTION
**Pull request by Oyyko**
## Why you open this Pull Request?
Fix the bug that prevent inner color operation in ellipse, arc and circle

### CODE REVIEW

**Comment by Oyyko** [comment]
项目编号如何计算

**Comment by darcy-shen** [comment]
还是ospp里面，新增，比如 23_x

**Comment by darcy-shen** [comment]
就这个而言，可以挂靠在新增画椭圆这个功能里面

**Comment by Oyyko** [comment]
OK

**Review by darcy-shen — APPROVED** [review]
Tested on macOS

**Pull request merged**
