### PR TITLE
[23_27] Draw arc: fix bug when 3 points in one line

### PR DESCRIPTION
**Pull request by Oyyko**
## Why you open this Pull Request?

Fix a bug about drawing arc. 

Bug: if 3 points in one line, it could be a semi-circle. But in previous version, we can not get a semi-circle. The program will give a line. Now it's fixed. We can get a semi-circle.

## What work have you done in the current Pull Request?
- [x] change the logic in drawing arc

### CODE REVIEW

**Comment by Oyyko** [comment]
This should be applied to https://github.com/XmacsLabs/mogan/pull/1254 also.

**Comment by darcy-shen** [comment]
就功能做了一个测试，确实修复了这个问题，但是画弧的方向反了

**Review by darcy-shen — CHANGES_REQUESTED** [review]
功能有问题，期望画弧默认是顺时针，这个pr实际在三点共线时是逆时针的

**Comment by Oyyko** [comment]
> 功能有问题，期望画弧默认是顺时针，这个pr实际在三点共线时是逆时针的

OK。这个比较容易改好。

**Comment by Oyyko** [comment]
现在应该可以了

**Pull request merged**
